server:
  port: 8061
spring:
  application:
    name: Zuul-Gateway
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost






















management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream